const colors = {
  light: {
    text: '#F0F0FF',
    tint: '#B347FF',
    background: '#080810',
    foreground: '#F0F0FF',
    card: '#0D0D1F',
    cardForeground: '#F0F0FF',
    primary: '#B347FF',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A30',
    secondaryForeground: '#F0F0FF',
    muted: '#141428',
    mutedForeground: '#7070A0',
    accent: '#FF3CAC',
    accentForeground: '#FFFFFF',
    destructive: '#FF4444',
    destructiveForeground: '#FFFFFF',
    border: '#1C1C35',
    input: '#1C1C35',
  },
  dark: {
    text: '#F0F0FF',
    tint: '#B347FF',
    background: '#080810',
    foreground: '#F0F0FF',
    card: '#0D0D1F',
    cardForeground: '#F0F0FF',
    primary: '#B347FF',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A30',
    secondaryForeground: '#F0F0FF',
    muted: '#141428',
    mutedForeground: '#7070A0',
    accent: '#FF3CAC',
    accentForeground: '#FFFFFF',
    destructive: '#FF4444',
    destructiveForeground: '#FFFFFF',
    border: '#1C1C35',
    input: '#1C1C35',
  },
  radius: 12,
};

export default colors;
